cookpad/expeditor

- expeditor.gemspec
- lib/expeditor/command.rb
- lib/expeditor/rich_future.rb
- spec/expeditor/command_spec.rb
- spec/expeditor/rich_future_spec.rb
I want to migrate to concurrent-ruby 1.0.0. But there are many breaking changes.
For a safe migration, I want to release a new version with 0.9 support first.
Please see a commit message for a detail of each change.
ref:
https://github.com/ruby-concurrency/concurrent-ruby/compare/v0.8.0...v0.9.0
https://github.com/ruby-concurrency/concurrent-ruby/blob/v0.9.0/CHANGELOG.md
> Support concurrent-ruby 0.9

- spec/expeditor/command_spec.rb
- spec/expeditor/rich_future_spec.rb
Fixed tests in https://github.com/k0kubun/expeditor/commit/1d70b125c6543eb84f87f4f89261a18eac51d010 of https://github.com/cookpad/expeditor/pull/2 to test properly and prevent random failure.
basically the same as rich_future_spec
- command1 is started
- worker is created (thread: 1, queue: 0)
- command1's task is enqueued (thread: 1, queue: 1)
- the worker pops queue (thread: 1, queue: 0)
- since mutex is locked, command1's task is blocked (thread: 1, queue: 0)
- command2 is started
- command2's task is enqueued (thread: 1, queue: 1)
- command3 is started
- since command3's task can't be enqueued (queue size is max_queue), handle_fallback is called
- RejectedExecutionError is raised
- RejectedExecutionError is rescued by #safe_execute
- RejectedExecutionError is set as reason in #fail
- …
> Test thread pool overflow properly

- expeditor.gemspec
- lib/expeditor/rich_future.rb
- spec/expeditor/rich_future_spec.rb
related to: https://github.com/cookpad/expeditor/pull/2
I fixed expeditor to work with concurrent-ruby v1.0.0.
> Support concurrent-ruby 1.0.0

- spec/expeditor/command_functions_spec.rb
Since my machine's spec is not so good, running command_functions_spec.rb takes much time.
I think 10000 is large enough to test large number of dependencies.
```
bundle exec rspec spec/expeditor/command_functions_spec.rb:93  96.80s user 5.73s system 103% cpu 1:39.16 total
```
```
bundle exec rspec spec/expeditor/command_functions_spec.rb:93  5.69s user 0.54s system 102% cpu 6.106 total
```
> Dcrease horizontal dependencies in spec

- .travis.yml
Now, we can't omit ".0" from "2.3.0".
> Test against Ruby 2.3

- lib/expeditor/service.rb
- spec/expeditor/service_spec.rb
Implement "1. Accessor to the current status in services" of #8 .
`Expeditor::Service#current_status` provides the current status of the status.
@cookpad/dev-infra 👓 ?
> Add Expeditor::Service#current_status

- lib/expeditor/service.rb
- spec/expeditor/service_spec.rb
Implement "2. Status reset" of #8.
`Expeditor::Service#reset_status!` re-generates the service's bucket and service status is reset.
@cookpad/dev-infra 👓 ?
> Add Expeditor::Service#reset_status!

- lib/expeditor/command.rb
- lib/expeditor/service.rb
- lib/expeditor/services/default.rb
- spec/expeditor/service_spec.rb
Implement "3. Fallbackable flag" of #8. ("Fallbackable is renamed to "fallback_enabled")
It provides "enabling and disabling" fallback blocks in the command.
@cookpad/dev-infra 👓 ?
> Add Expeditor::Service#fallback_enabled

- CHANGELOG.md
- README.md
- examples/example.rb
- lib/expeditor/command.rb
- spec/expeditor/circuit_break_function_spec.rb
- spec/expeditor/command_functions_spec.rb
- spec/expeditor/command_spec.rb
- spec/expeditor/retry_function_spec.rb
- spec/expeditor/service_spec.rb
Currently, `with_fallback` behavior is complexity. This cause is cloning in `with_fallback` method.
This change is required from #13 .
> Don't clone when `with_fallback` is called

- .travis.yml
- CHANGELOG.md
- README.md
- expeditor.gemspec
- Remove MRI 2.0.0 from .travis.yml
- Add `required_ruby_version` into gemspec
- Add message of support ruby version into README
> Drop support for MRI 2.0.x

- spec/expeditor/command_functions_spec.rb
Because process crashes if create 2048 threads in OS X.
e.g.
```sh
$ bundle exec rspec
Expeditor::Bucket
#increment
with same status
should be increased
across statuses
should be ok
#total
with no limit exceeded
should be ok
with limit exceeded
should be ok
Expeditor::Command
circuit break function
with circuit break
should reject execution
should not count circuit break
with circuit break and wait
should reject execution and back
with circuit break (large case)
should be ok
with dependency's error of circuit break
should not fall deadlock
Expeditor::Command
dependencies function
with normal and no sleep
should be ok
with normal and sleep
should start dependencies concurrently
with failure
should throw error DependencyError
with sleep and failure
should throw error immediately
with large …
```
> Reduce large number for test case

- CHANGELOG.md
- lib/expeditor/command.rb
- lib/expeditor/errors.rb
- spec/expeditor/circuit_break_function_spec.rb
- spec/expeditor/command_spec.rb
I've changed `Command#set_fallback` behavior. The change is breaking.
After `Command#start` is called, can't set fallback.
Current behavior
---
```ruby
command = Expeditor::Command.new{xxx}
command.start
command.with_fallback{xxx} # => it's allowed
```
Changed behavior
----
```ruby
command = Expeditor::Command.new{xxx}
command.start
command.with_fallback{xxx} # => throw AlreadyStartedError
```
If the above code exists, please fix to the following code.
```ruby
command = Expeditor::Command.new{xxx}
command.with_fallback{xxx}
command.start
```
Current behavior is not natural. And in #13 's implementation, keeping the behavior is hard. So, I've changed it.
> Do not allow set_fallback call after command is started

- spec/expeditor/command_functions_spec.rb
- spec/expeditor/command_spec.rb
- spec/spec_helper.rb
- spec/support/command.rb
- DRY helper code in spec
- remove unnecessary return value of `error_command`
> Refactor spec

- CHANGELOG.md
- README.md
- lib/expeditor/command.rb
- spec/expeditor/command_functions_spec.rb
- spec/expeditor/command_spec.rb
- spec/expeditor/current_thread_function_spec.rb
I've added a feature to execute a command on current thread.
Currently, we can execute a command on current thread by the following code.
```ruby
require 'expeditor'
require 'concurrent/executor/immediate_executor'
service = Expeditor::Service.new executor: Concurrent::ImmediateExecutor.new
command = Expeditor::Command.new(service: service){puts 1; sleep 1; puts 2}
puts 'start'
command.start
puts 'end'
```
However, it's complexity. So, I've added `Command#run` method to execute on current thread.
The following code works same as the above.
```ruby
service = Expeditor::Service.new
command = Expeditor::Command.new(service: service){puts 1; sleep 1; puts 2}
puts 'start'
command.run  # use run instead of start
puts 'end'
```
Naming of `run` is inspired by `exec.Command` of Golang. …
> Execute a command on current thread

- CHANGELOG.md
- lib/expeditor/version.rb
- Add a `current_thread` option of `Expeditor::Command#start` method to execute a task on current thread [#13](https://github.com/cookpad/expeditor/pull/13)
- Drop support for MRI 2.0.x [#15](https://github.com/cookpad/expeditor/pull/15)
- Deprecate Expeditor::Command#with_fallback. Use `set_fallback` instead [#14](https://github.com/cookpad/expeditor/pull/14)
- Do not allow set_fallback call after command is started. [#18](https://github.com/cookpad/expeditor/pull/18)
I'll merge and release to rubygems after test passed
> Bump up to 0.5.0

- lib/expeditor/command.rb
This is follow-up PR for https://github.com/cookpad/expeditor/pull/21.
This refactoring also looks to me.
FYI @ganmacs @cookpad/dev-infra
> Stop using #send to set value to Concurrent::IVar

- README.md
- examples/circuit_breaker.rb
- lib/expeditor/bucket.rb
- lib/expeditor/service.rb
- spec/expeditor/service_spec.rb
Expeditor collects metrics in a gradual manner as in README.
`#current_status` gets metrics only from split short time window and it's
not the "status" in the Expeditor's context. To return proper status,
use `Bucket#total` instead.
@makimoto @cookpad/dev-infra How about this change?
> Return proper status of service

- README.md
- lib/expeditor/service.rb
Current default configuration of `non_break_count` for circuit breaking feature is a little bit large to typical usecases. I propose to reduce this number.
I refer original Hytrix's default configuration value and `20` service calls during 10 seconds can be more reasonable value to me: https://github.com/Netflix/Hystrix/wiki/Configuration#circuitBreaker.requestVolumeThreshold
@cookpad/dev-infra What do you think of this?
cc @amutake just FYI
> Improve default configuration of circuit breaker

- expeditor.gemspec
User should be able to select whether use or not:
https://github.com/ruby-concurrency/concurrent-ruby/blob/v1.0.5/README.md#note-for-gem-developers
@cookpad/dev-infra Any thoughts?
> We should not depend on this in a gemspec

- .gitignore
- lib/expeditor/service.rb
- spec/expeditor/bucket_spec.rb
- spec/expeditor/circuit_break_function_spec.rb
- spec/expeditor/command_functions_spec.rb
- spec/expeditor/command_spec.rb
- spec/expeditor/current_thread_function_spec.rb
- spec/expeditor/retry_function_spec.rb
- spec/expeditor/rich_future_spec.rb
- spec/expeditor/service_spec.rb
- spec/expeditor/status_spec.rb
- spec/spec_helper.rb
And also
- Introduce RSpec configuration with `rspec --init` so that measure test execution time.
- Ignore `.ruby-version` file.
@cookpad/dev-infra Please take a look.
> Fix broken, fragile and slow tests around circuit breaker

- expeditor.gemspec
And its "ext" gem.
In my opinion, this is because a gem should not limit possible
compatibility in its gemspec.
@cookpad/dev-infra How about this?
> Don't limit upper version of concurrent-ruby

- lib/expeditor/bucket.rb
- spec/expeditor/bucket_spec.rb
Previously the logic is wrong and we cut the passing size to smaller
than needed. See more detail in the commit and code doc.
@cookpad/dev-infra Please take a look.
---
I also plan to refactoring class name of `Bucket` and split its methods into 2 classes because current names are confusing: actually a `Bucket` has multiple pockets or spaces to hold `Status`s and its pockets are linked as circulated, and also a `Bucket`'s pockets are sliced by time.
> Fix bug on cutting passing size

- lib/expeditor/command.rb
- spec/expeditor/command_functions_spec.rb
- spec/expeditor/command_spec.rb
Most of changes are just refactoring. But 171b0aa changes a behavior of the test. I believe the test was broken accidentally and by this change it gets back original functionality.
@cookpad/dev-infra Please take a look at this 👀
> More reliable and fast tests

- Rakefile
- expeditor.gemspec
- lib/expeditor/service.rb
- scripts/command_performance.rb
Fix possible race condition: If 2 commands (A, B) are given where both
commands have same Service instance (S). Both commands run and called
Service#open? at the same moment. Thread for A (thA) proceed to calling
Service#calc_open in calling Service#open?, then Service#calc_open
returned `true` at that time. At next moment, S's `@breaking` was set to
`true` in thA, then the thread scheduler decided to switch to run thB.
In thB, Service#open? was just called but since `@breaking` was set to
`true` by thA just a memont ago. So thB goes into if-then branch and
refer `@break_start`. The problem is here, the `@breaking` was set by
thA but `@break_start` was not yet set by thA, so thB's next
computation, which is `Time.now - @break_start` goes wrong result.
To fix the problem, simply …
> Service#open? is called concurrently

- spec/expeditor/command_spec.rb
Since we don't wait this `sleep_time` and this makes the test case
more clear.
Ref: https://travis-ci.org/cookpad/expeditor/jobs/227522168
@cookpad/dev-infra FYI
> Set larger sleep_time to be more stable test

- lib/expeditor/command.rb
- lib/expeditor/service.rb
- lib/expeditor/services/default.rb
- spec/expeditor/circuit_break_function_spec.rb
- spec/expeditor/service_spec.rb
The naive implementation of sleep feature is aad8f17, but the problem is shown by 5cebcec that we want to allow only single requests when test the service is back to healthy or not. So I changed the interface by 1b8a21b.
@cookpad/dev-infra Please take a look at this.
> Implement sleep feature on circuit breaker

- lib/expeditor/service.rb
This fixes the following warnings that are printed when using this gem with Ruby 2.7:
Running `bundle exec rspec` at expeditor master:
```
/Users/r7kamura/src/github.com/r7kamura/expeditor/lib/expeditor/service.rb:111: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/r7kamura/src/github.com/r7kamura/expeditor/lib/expeditor/rolling_number.rb:10: warning: The called method `initialize' is defined here
```
> Fix Ruby 2.7 keyword arguments deprecation warning
